### ISSUE TITLE
Problem with Python 3.8

### ISSUE THREAD

**Issue by GKrauseDB** [aperezhortal/flake8-dashboard#2]
I got the following error when running flake8-dashboard on windows for a project:

```
 flake8 keywords --format=dashboard
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\GeorgKrause\workspace\testautomation\env\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8\main\application.py", line 393, in run
    self._run(argv)
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8\main\application.py", line 382, in _run
    self.report()
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8\main\application.py", line 376, in report
    self.formatter.stop()
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8_dashboard\plugin.py", line 161, in stop
    errors_by_folder_or_file = self._aggregate_by_folder_or_file(error_db)
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\flake8_dashboard\plugin.py", line 411, in _aggregate_by_folder_or_file
    sel = total_errors_by_file.index.get_level_values(0).str.match(f"^{_path}\/")
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\pandas\core\strings.py", line 1954, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\pandas\core\strings.py", line 2770, in match
    result = str_match(self._parent, pat, case=case, flags=flags, na=na)
  File "c:\users\georgkrause\workspace\testautomation\env\lib\site-packages\pandas\core\strings.py", line 821, in str_match
    regex = re.compile(pat, flags=flags)
  File "c:\program files\python38\lib\re.py", line 250, in compile
    return _compile(pattern, flags)
  File "c:\program files\python38\lib\re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\program files\python38\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "c:\program files\python38\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "c:\program files\python38\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "c:\program files\python38\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "c:\program files\python38\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 16
```

**Comment by aperezhortal** [comment]
Hi @GKrauseDB, thanks for using flake8-dashboard! 

I will try to set up a windows environment and reproduce the error. The package was only tested on Linux, which uses "/" as separators. My guess is that the windows paths containing the "\" separators are not treated as literals and try to scape them.

**Comment by GKrauseDB** [comment]
Hi @aperezhortal 

its quite interesting, if I use each sub directory of `keywords`, there is no error. But each subdirectory has some subdirectories again, but only the root dir makes trouble. 

If you need any more information to debug this, just let me know! I can provide any information you need :)

**Comment by GKrauseDB** [comment]
I am not really sure how this plugin works. But if I get this correctly there is this `error_db` which contains all the errors. When adding the errors it might be a good idea to use `os.path.normpath(filename)` to have platform-independend file names and prevent errors.

Besides this it seems that the reg ex https://github.com/aperezhortal/flake8-dashboard/blob/master/flake8_dashboard/plugin.py#L452 causes the problem.

**Comment by aperezhortal** [comment]
PR #3 should close this issue.
