### ISSUE TITLE
AttributeError: type object 'DashboardReporter' has no attribute 'name' with Flake8 v.3.x

### ISSUE THREAD

**Issue by mcosta74** [aperezhortal/flake8-dashboard#4]
# Description
Looks like the plugin is not valid with flake8 `v3.8.x`

## Steps to reproduce
```
$ pip install flake8 flake8-dashboard
$ flake8 --format=dashboard --title='My Dashboard' src/
```

### Expected results
The process finished correctly and the dashboard is produced

## Current Results
```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/usr/local/lib/python3.8/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.8/site-packages/flake8/main/application.py", line 329, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.8/site-packages/flake8/main/application.py", line 167, in register_plugin_options
    self.formatting_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python3.8/site-packages/flake8/plugins/manager.py", line 433, in register_options
    list(self.manager.map(call_register_options))
  File "/usr/local/lib/python3.8/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flake8/plugins/manager.py", line 402, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flake8/plugins/manager.py", line 215, in register_options
    with optmanager.group(self.plugin_name):
  File "/usr/local/lib/python3.8/site-packages/flake8/plugins/manager.py", line 120, in plugin_name
    self._plugin_name = self.plugin.name
AttributeError: type object 'DashboardReporter' has no attribute 'name'
```

**Comment by aperezhortal** [comment]
Hi @mcosta74. Thanks for reporting this issue! 

The name attribute was missing in the plugin. Commit 505c4a6 fixes it. 

Feel free to reopen it if you are still experiencing issues.

**Comment by mcosta74** [comment]
Hi, any ETA for a release with the fix?

**Comment by aperezhortal** [comment]
I'll try to do a minor release over the weekend.
