### ISSUE TITLE
AttributeError: type object 'DataFrame' has no attribute 'severity' with Flake8 v6

### ISSUE THREAD

**Issue by wfzyx** [aperezhortal/flake8-dashboard#7]
As title says, trying to use it flake8 v6 will crash when trying to fetch the severity column on the dataframe.

I tried fixing it myself, but I'm not super familiar with how the flake8 plugin infrastructure works to test it locally.

```
Traceback (most recent call last):
  File "/home/victor/.local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.local/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/victor/.local/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/victor/.local/lib/python3.10/site-packages/flake8/main/application.py", line 188, in _run
    self.report()
  File "/home/victor/.local/lib/python3.10/site-packages/flake8/main/application.py", line 183, in report
    self.formatter.stop()
  File "/home/victor/.local/lib/python3.10/site-packages/flake8_dashboard/plugin.py", line 161, in stop
    error_severity.index, error_severity.severity.values
  File "/home/victor/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'severity'

```

**Comment by biplab-biswas-ai** [comment]
Pin your pandas version to <2. This repo's requirements.txt should pin the pandas version to lower than 2. Mine worked after I installed flake8-dashboard along with pandas==1.3.5.
Hope this helps.
